### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by Vechro** [sguest/RomanJS#1]
This library is awesome and works exactly like needed, but working with node it'd be preferable to have the library on npm so it can be imported with ease. I don't know much about publishing to npm (I don't imagine it's too difficult) but adding a package.json would be a good start.

**Comment by sguest** [comment]
Wow, blast from the past. I never expected anyone to actually find/use this.

Package is [@sguest/roman-js](https://www.npmjs.com/package/@sguest/roman-js) since there were enough other similarly-named packages I couldn't come up with a good one that didn't conflict.
